# Generated by Django 3.0.3 on 2020-04-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200410_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Date',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
